// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG5ATBEGI-5y89cEVu-9Zb_7wexW3WnvU',
    appId: '1:380211709608:web:ac6346f36579553678649d',
    messagingSenderId: '380211709608',
    projectId: 'smarthomeapp-elias',
    authDomain: 'smarthomeapp-elias.firebaseapp.com',
    storageBucket: 'smarthomeapp-elias.firebasestorage.app',
    measurementId: 'G-RZCHP9597B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJf15HLksZudcKrD3DUJWFJdNvf72jOVA',
    appId: '1:380211709608:android:2223bab1a90d673578649d',
    messagingSenderId: '380211709608',
    projectId: 'smarthomeapp-elias',
    storageBucket: 'smarthomeapp-elias.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk_lliNpS3fX-AILRnJDKgq-Ggv1FYbK0',
    appId: '1:380211709608:ios:45cb88e587551de178649d',
    messagingSenderId: '380211709608',
    projectId: 'smarthomeapp-elias',
    storageBucket: 'smarthomeapp-elias.firebasestorage.app',
    iosBundleId: 'com.example.smarthomeappElias',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk_lliNpS3fX-AILRnJDKgq-Ggv1FYbK0',
    appId: '1:380211709608:ios:45cb88e587551de178649d',
    messagingSenderId: '380211709608',
    projectId: 'smarthomeapp-elias',
    storageBucket: 'smarthomeapp-elias.firebasestorage.app',
    iosBundleId: 'com.example.smarthomeappElias',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG5ATBEGI-5y89cEVu-9Zb_7wexW3WnvU',
    appId: '1:380211709608:web:441fbf104c24c79d78649d',
    messagingSenderId: '380211709608',
    projectId: 'smarthomeapp-elias',
    authDomain: 'smarthomeapp-elias.firebaseapp.com',
    storageBucket: 'smarthomeapp-elias.firebasestorage.app',
    measurementId: 'G-1SRQSDBGDV',
  );
}
